# Generated by Django 4.1.7 on 2023-05-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=100)),
                ('clogo', models.FileField(upload_to='')),
                ('cname', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=100)),
                ('package', models.IntegerField(max_length=10)),
                ('status', models.CharField(default='Active', editable=False, max_length=100)),
            ],
            options={
                'db_table': 'placement',
            },
        ),
    ]
