# Generated by Django 4.1.7 on 2023-05-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement_model',
            name='package',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
